# Generated by Django 4.2.6 on 2024-01-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Lengkap', models.CharField(max_length=100)),
                ('Panggilan', models.CharField(max_length=100)),
            ],
        ),
    ]
